### ISSUE TITLE
why do you use ZeroMQ

### ISSUE THREAD

**Issue by HoangNgo88** [UnterrainerInformatik/htl-zeromq#2]
Hi, I am reading your project and I love this project
I have a question, why do you choose ZeroMQ in your project instead of others like RabbitMQ or Kafka, are there any special feature but others dont have it. Can you share me about it. I am wondering when I should choose ZeroMQ instead of others like RabbitMQ or Kafka

**Comment by guFalcon** [comment]
Hi there!

Those three are pretty different and you wouldn't exchange those without some serious consideration.

RabbitMQ is a general-purpose message broker that supports many different protocols. You can use the different Exchanges to achieve different routing of messages.
It uses what is called a 'smart broker / dumb consumer' model. That means that the server keeps track of all the messages and if it should keep it, or delete it because no one is gonna read them anymore.

Kafka is a message bus built for vast data streams with very high throughput and replay capability. It is very fast, handles a lot of data, and scales pretty well. On the other hand, it is not as neat and compact as other implementations and the frequent updates could be a pain in the ass, to be frank.
It uses what is called a 'dumb broker / smart consumer' model, which means that the server just keeps all messages for a given time. It relies on the consumers to decide whether they needed those messages or not, dealing them to all consumers alike.

ZeroMQ is a simple, yet very powerful framework you can use to write your own message-broker implementations with. You'd use it when none of the other implementations fits your needs. Or you would use it to do simple process-to-process communication between two servers, for instance, because it has such a neat and simple data abstraction for socket-to-socket communication.

The reason why I chose ZeroMQ is because this repository is a simple example I use for teaching at school :)

Sincerely, Gerald

**Comment by guFalcon** [comment]
test

 

From: Hoang Ngo ***@***.***> 
Sent: Freitag, 27. Jänner 2023 05:15
To: UnterrainerInformatik/htl-zeromq ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [UnterrainerInformatik/htl-zeromq] why do you use ZeroMQ (Issue #2)

 

Hi, I am reading your project and I love this project
I have a question, why do you choose ZeroMQ in your project instead of others like RabbitMQ or Kafka, are there any special feature but others dont have it. Can you share me about it. I am wondering when I should choose ZeroMQ instead of others like RabbitMQ or Kafka
